export const SAVE_AUTHORIZATION_DATA = "SAVE_AUTHORIZATION_DATA";
export const CHANGE_FIRST_LOGIN_STATUS = "CHANGE_FIRST_LOGIN_STATUS";
export const LOGOUT = "LOGOUT";
export const UPDATE_ACTIVITY_STATUS = "UPDATE_ACTIVITY_STATUS";
